name: ui_kit
description: Paasel design tokens, theme, and reusable widgets.
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
